

map_string = """\
              OOOOOOOOOOOOOOOOOOOOO
              OOOOOOOOSMMMMJJJJJJJO
              OSSSSSJJJJMMJJJJJJJOO
              OSSSSSSSSSMMJJJJJJOOO
              OSSSSSJJJJJJJJJJJJOOO
              OSSSSSJJJDDJJJSJJJOOO
              OSSJJJJJDDDJJJSSSSOOO
              OOSSSSJJJDDJJJSOOOOOO
              OSSSJJJJJDDJJJJJJJOOO
              OSSSSJJJJDDJJJJOOOOOO
              OOSSSSJJJJJJJJOOOOOOO
              OOOSSSSJJJJJJJOOOOOOO
              OOOOOOOOOOOOOOOOOOOOO"""

test_map = Map(map_string)
test_map.show_map()